apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: {{ .Chart.Name }}
    component: mongo-express
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}
    component: mongo-express
    release: {{ .Release.Name }}
